### ISSUE TITLE
Vue 3

### ISSUE THREAD

**Issue by PhilippHandle** [chimera-js/vue-chimera#17]
Will chimera get Vue 3 support?

**Comment by SasanFarrokh** [comment]
I'll start working on it soon, but there will be a lot changes, Vue Chimera 4 will be completely on composition api, 
If you like to try something like vue-chimera with vue 3 use this:

[https://github.com/Kong/swrv](https://github.com/Kong/swrv)

**Comment by PhilippHandle** [comment]
Thanks, I will check it out.

Thanks for your work
