### ISSUE TITLE
Prevent the duplication of auto refreshing data.

### ISSUE THREAD

**Issue by jacksun101** [chimera-js/vue-chimera#2]
Thanks for the plugin. It's awesome.

I use the feature of refreshing data by specifying the "interval" property. However, it seems to duplicate the setInterval process every time I enters the route. How can I prevent from it? Can I stop the interval process when I leave current route?

**Comment by SasanFarrokh** [comment]
Thanks a lot.

Sorry for these bugs, I'm trying to fix as quick as possible.
I published a new release v2.1.2, Issue have been solved.
you can upgrade to vue-chimera@^2.1.2
