### ISSUE TITLE
New feature suggest - pause & resume

### ISSUE THREAD

**Issue by jacksun101** [chimera-js/vue-chimera#3]
Thanks again for this awesome plugin.

While I was using the feature of setting "interval" property for making continuously calls, soon I realized that I need to pause and resume the looping. For example, I use it to update a table every 10 seconds, and then I need to pause the calling when dialog is opened.

Currently, I use cancel() to stop the looping, and then use reload(). However, after reloading my resource the interval is not working, instead it's calling just once.

**Comment by SasanFarrokh** [comment]
On version before 2.1.2:
  You can use `resource.clearInterval` and `resource.setInterval(5000)` to start and stop interval.
As prior to version 2.2.0:
Changed method names to be more convenient `startInterval` and `stopInterval`.
Also you're not have to pass miliseconds parameter to `setInterval`, it uses the assigned one.

Thanks.
