### ISSUE TITLE
Event seems not working

### ISSUE THREAD

**Issue by jacksun101** [chimera-js/vue-chimera#4]
According to the document, the event can be handled like this. But I don't get the resource as described as below.

```
chimera: {
      users: {
        url: '/users',
        on: {
          'success': (resource) => {
              console.log(resource) // THIS IS UNDEFINED.
          }
        }
      }
    }

**Comment by SasanFarrokh** [comment]
Upgrade to latest version v2.4.3
If issue still exists let me know.

Thanks
