### ISSUE TITLE
need a flag show the Resource is looping

### ISSUE THREAD

**Issue by acgergu** [chimera-js/vue-chimera#6]
`chimera:{
    getAllInfos:{
      url:"xxx",
      interval:5000
    }
  }`

I see #3 

if i stopInterval(),i can't find a flag judge isLooping().
so i `delete this.$chimera.getAllInfos._interval_id` and use `this.$chimera.getAllInfos.["_interval_id"]` to judge.

This way is not elegant at all. I think it has the potential for improvement. Please add a method like isLooping() help to judge.

my first time take issue on GitHub, Forgive my Chinese style English

**Comment by SasanFarrokh** [comment]
New major version `3.0.0` published.
You can use `looping` property 

http://localhost:8080/guide/endpoint.html#properties
