### ISSUE TITLE
Why chimera is null in mounted?

### ISSUE THREAD

**Issue by wizardnet972** [chimera-js/vue-chimera#9]
I want to use vue-chimera so I do as say in the readme.

```
npm install vue-chimera

import Vue from 'vue'
import VueChimera from 'vue-chimera'

Vue.use(VueChimera)
```

in my component:
```
chimera = {
    user: () => `https://randomuser.me/api/?results=1`
};
```

But I get this.$chimera null. The problem I see is that chimera option needs to be provided for new Vue. It seems that decorators are ok here but the lib isn't. I did a quick check and it seems that the lib has a major bug, and if it's true I'm not sure why it wasn't reported.This part [https://github.com/chimera-js/vue-chimera/blob/master/src/mixin.js#L6-L10](https://github.com/chimera-js/vue-chimera/blob/master/src/mixin.js#L6-L10) makes _chimera (and then $chimera too) unavailable in nested comps because $options aren't fully inherited in components. 

[The app code on CodeSandbox.io](https://codesandbox.io/s/vue-class-component-example-jd9ut)
```
<template>
  <div class="info">blabla</div>
</template>

<style>
div {
  height: 2000px;
}
</style>

<script>
import { Vue, Component } from "vue-property-decorator";

@Component
export default class userManager extends Vue {

  chimera = {
    user: () => `https://randomuser.me/api/?results=1`
  };

  mounted() {
    console.log("in mounted");

    console.log({ ch: this.$chimera }); // <---- null?

    this.$chimera.user.execute().then(res => {
      console.log({ res });
    });
  }
}
</script>
```

**Comment by SasanFarrokh** [comment]
Currently this plugin does not fully support typescript. However, there is workarounds to create custom declaration files or something.

You're currently adding chimera as a data inside your class file, if you want to use `vue-property-decorator`, here is how to add chimera:

```javascript
import { Vue, Component } from "vue-property-decorator";

@Component({
     chimera: {
         user:  'https://randomuser.me/api/?results=1'
     };
})
export default class userManager extends Vue {
  mounted() {
    console.log("in mounted");

    console.log({ ch: this.$chimera }); // <---- null?

    this.$chimera.user.execute().then(res => {
      console.log({ res });
    });
  }
}
```

Hopefully soon vue chimera 3 will be released and there will be typescript support.
Thanks

**Comment by wizardnet972** [comment]
@SasanFarrokh Perfect! Works!
This is a awesome package and great idea! Thank you a lot :)
